version: "3.9"
volumes:
  songs_data:  # Create a volume core_data that will contain the data for 'songs_persistence', such that when the container is stopped / crashes, the data remains.
  login_data:
  friends_data:
  playlist_data:
  share_data:
  feed_data:
services:

  songs_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres  # Can be any username & password combination, but we need to use the same combination in the code in 'songs'
      - POSTGRES_PASSWORD=postgres
    volumes:
      # Map the songs_persistence folder to the docker-entrypoint-initdb.d folder in the container.
      # This will ensure that the necessary files are present in the container for initializing the database(s)
      - ./songs_persistence/:/docker-entrypoint-initdb.d
      # Map the psql data from the container to a virtual volume, thus preserving the data after the container is stopped.
      - songs_data:/var/lib/postgresql/data
#    networks:
#      - songs_net

  login_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      # Map the login_persistence folder to the docker-entrypoint-initdb.d folder in the container.
      # This will ensure that the necessary files are present in the container for initializing the database(s)
      - ./login_persistence/:/docker-entrypoint-initdb.d
      - login_data:/var/lib/postgresql/data

  #    networks:
#      - login_net

  friends_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./friends_persistence/:/docker-entrypoint-initdb.d
      - friends_data:/var/lib/postgresql/data
#    networks:
#      - friend_net

  playlist_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./playlist_persistence/:/docker-entrypoint-initdb.d
      - playlist_data:/var/lib/postgresql/data
#    networks:
#      - playlist_net

  share_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./share_persistence/:/docker-entrypoint-initdb.d
      - share_data:/var/lib/postgresql/data
#    networks:
#      - share_net

  feed_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./feed_persistence/:/docker-entrypoint-initdb.d
      - feed_data:/var/lib/postgresql/data
#    networks:
#      - feed_net

  songs:
    build: ./songs
    ports:
      - 5001:5000
    depends_on:
      - songs_persistence
#    networks:
#      - songs_net
#      - general

  login:
    build: ./login
    ports:
      - 5002:5000
    depends_on:
      - login_persistence
#    networks:
#      - login_net
#      - general

  friends:
    build: ./friends
    ports:
      - 5003:5000
    depends_on:
      - friends_persistence
#    networks:
#      - general
#      - friend_net

  playlist:
    build: ./playlist
    ports:
      - 5004:5000
    depends_on:
      - playlist_persistence
#    networks:
#      - general
#      - playlist_net

  share:
    build: ./share
    ports:
      - 5005:5000
    depends_on:
      - share_persistence
#    networks:
#      - share_net
#      - general

  feed:
    build: ./feed
    ports:
      - 5006:5000
    depends_on:
      - feed_persistence


  gui:
    build: ./gui
    ports:
      - 5000:5000

